// <auto-generated />
namespace CampingdoZe2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class tipoproduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipoproduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201712052218227_tipoproduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
